#!/usr/bin/env python3
"""Convert juppee's claudepix splash header into firmware/src/buddy_animations.h.

The source (research/buddy-sprites/csb_splash_animations.h) stores fixed 20x20
frames with a 10-colour palette. Upstream's engine wants bounding-box crops
placed on the 55x37 art stage inside a 60x60 grid (see splash.cpp
compose_stage). Each animation is:

  1. remapped so every palette entry that is pure black becomes index 0
     (background) and the rest are compacted to 1..n,
  2. cropped to the union bounding box of non-background cells over all frames,
  3. upscaled `scale`x with nearest neighbour,
  4. centred horizontally, feet on the stage bottom like official Clawd
     (ox/oy are stage coordinates; oy is clamped at 0 for very tall art).

The loop region is the whole file: these sprites have no intro or outro.
Only the names in KEEP are emitted: the buddy states the official art has no
close match for. Everything else plays official Clawd.

Usage: python tools/import_buddy_sprites.py [--scale 2] [--in PATH] [--out PATH]
"""
import argparse
import re
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_IN = ROOT / "research" / "buddy-sprites" / "csb_splash_animations.h"
DEFAULT_OUT = ROOT / "firmware" / "src" / "buddy_animations.h"
SRC_W = 20
GRID = 60
STAGE_W, STAGE_H = 55, 37
ANCHOR_X, ANCHOR_Y = (GRID - STAGE_W) // 2, (GRID - STAGE_H) // 2   # 2, 11
KEEP = ("allow", "limit", "expression surprise", "expression sleep")


@dataclass
class Anim:
    name: str
    palette: list
    frames: list   # list[list[int]], each SRC_W*SRC_W
    holds: list


@dataclass
class Converted:
    name: str
    ident: str
    w: int
    h: int
    ox: int
    oy: int
    loop_start: int
    loop_end: int
    palette: list
    frames: list   # list[list[int]], each w*h
    holds: list


def _nums(body):
    return [int(x, 0) for x in re.findall(r"0x[0-9A-Fa-f]+|\d+", body)]


def parse_header(text):
    arrays = {}
    for m in re.finditer(r"static const uint16_t (\w+)\[\d+\] = \{([^}]*)\};", text):
        arrays[m.group(1)] = _nums(m.group(2))
    for m in re.finditer(r"static const uint8_t (\w+)\[\d+\]\[400\] = \{(.*?)\n\};", text, re.S):
        arrays[m.group(1)] = [_nums(f) for f in re.findall(r"\{([^{}]*)\}", m.group(2))]
    table = re.search(r"splash_anims\[SPLASH_ANIM_COUNT\] = \{(.*?)\n\};", text, re.S).group(1)
    out = []
    for m in re.finditer(r'\{"([^"]+)",\s*"[^"]*",\s*\d+,\s*(\w+),\s*(\w+),\s*(\w+)\}', table):
        name, pal, frames, holds = m.groups()
        out.append(Anim(name, arrays[pal], arrays[frames], arrays[holds]))
    return out


def select(anims, names):
    by_name = {a.name: a for a in anims}
    missing = [n for n in names if n not in by_name]
    if missing:
        raise KeyError(f"not in source header: {', '.join(missing)}")
    return [by_name[n] for n in names]


def convert(anim, scale=2):
    # 1. background remap + palette compaction
    used = sorted({c for f in anim.frames for c in f})
    remap, palette = {}, [0x0000]
    for idx in used:
        colour = anim.palette[idx]
        if colour == 0x0000:
            remap[idx] = 0
        else:
            remap[idx] = len(palette)
            palette.append(colour)
    if len(palette) > 16:
        raise ValueError(f"{anim.name}: {len(palette)} colours > 16")
    frames = [[remap[c] for c in f] for f in anim.frames]

    # 2. union bounding box
    rows = [r for f in frames for r in range(SRC_W) if any(f[r * SRC_W:(r + 1) * SRC_W])]
    cols = [c for f in frames for c in range(SRC_W)
            if any(f[r * SRC_W + c] for r in range(SRC_W))]
    r0, r1, c0, c1 = min(rows), max(rows), min(cols), max(cols)

    # 3. crop + nearest-neighbour upscale
    w, h = (c1 - c0 + 1) * scale, (r1 - r0 + 1) * scale
    scaled = []
    for f in frames:
        scaled.append([f[(r0 + y // scale) * SRC_W + (c0 + x // scale)]
                       for y in range(h) for x in range(w)])

    # 4. centre horizontally, stand on the stage bottom (see compose_stage)
    if w > 50 or h > 49:
        raise ValueError(f"{anim.name}: {w}x{h} does not fit the stage")
    ox = (GRID - w) // 2 - ANCHOR_X
    oy = max(0, STAGE_H - h)

    ident = re.sub(r"\W+", "_", anim.name).strip("_")
    return Converted(anim.name, ident, w, h, ox, oy, 0, len(frames) - 1,
                     palette, scaled, list(anim.holds))


def emit(items):
    lines = [
        "// ============================================================",
        "// Buddy animations: generated by tools/import_buddy_sprites.py from",
        "// research/buddy-sprites/csb_splash_animations.h. Do not edit by hand.",
        "// Played when the host names one in the BLE payload (\"a\").",
        "// Include after splash_animations.h (for splash_anim_def_t).",
        "// ============================================================",
        "#pragma once",
        "#include <stdint.h>",
        "",
    ]
    for c in items:
        p = f"buddy_{c.ident}"
        lines.append(f"static const uint16_t {p}_palette[{len(c.palette)}] = {{"
                     + ",".join(f"0x{v:04X}" for v in c.palette) + "};")
        lines.append(f"static const uint8_t {p}_frames[{len(c.frames) * c.w * c.h}] = {{")
        for f in c.frames:
            lines.append("    " + ",".join(map(str, f)) + ",")
        lines.append("};")
        lines.append(f"static const uint16_t {p}_holds[{len(c.holds)}] = {{"
                     + ",".join(map(str, c.holds)) + "};")
        lines.append("")
    lines.append(f"#define BUDDY_ANIM_COUNT {len(items)}")
    lines.append("static const splash_anim_def_t buddy_anims[BUDDY_ANIM_COUNT] = {")
    for c in items:
        p = f"buddy_{c.ident}"
        lines.append(f'    {{"{c.name}", "buddy", {c.w}, {c.h}, {c.ox}, {c.oy}, '
                     f"{len(c.frames)}, {c.loop_start}, {c.loop_end}, {len(c.palette)}, "
                     f"{p}_palette, {p}_frames, {p}_holds}},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--in", dest="src", type=Path, default=DEFAULT_IN)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--scale", type=int, default=2)
    args = ap.parse_args()
    items = [convert(a, args.scale) for a in select(parse_header(args.src.read_text()), KEEP)]
    args.out.write_text(emit(items))
    total = sum(len(c.frames) * c.w * c.h for c in items)
    print(f"wrote {args.out} ({len(items)} animations, {total / 1024:.0f} KB of frames)")


if __name__ == "__main__":
    main()
